
// 超级管理员所有权限
const modules = [
  {
    name: '开屏广告',
    id: '0-0-0',
    auth: 15,
    path: 'app-launch-ad',
  }, {
    id: '0-0-1-0',
    name: '机票首页',
    auth: 15,
    path: 'airTickets',
  },
  {
    id: '0-0-1-1',
    name: '酒店首页',
    auth: 15,
    path: 'hotel',
  },
  {
    id: '0-0-1-2',
    name: '探索页',
    auth: 15,
    path: 'explorationPage',
  }, {
    id: '0-0-2-0',
    name: '栏目模块',
    auth: 15,
    path: 'column',
  },
  {
    id: '0-0-2-1',
    name: '何时出发',
    auth: 15,
    path: 'leave',
  },
  {
    id: '0-0-2-2',
    name: '动态航线',
    auth: 15,
    path: 'route',
  },
  {
    id: '0-0-2-3',
    name: '目的地推荐',
    auth: 15,
    path: 'destination',
  },
  {
    id: '0-0-2-4',
    name: '自定义栏目',
    auth: 15,
    path: 'custom',
  }, {
    id: '0-0-3',
    name: '航线配置',
    auth: 15,
    path: 'routeConfig',
  }, {
    id: '0-0-4-0',
    name: '推荐名单',
    auth: 15,
    path: 'recommended',
  },
  {
    id: '0-0-4-1',
    name: '酒店列表',
    auth: 15,
    path: 'list',
  }, {
    id: '0-0-5',
    name: '运营推送',
    auth: 15,
    path: 'operationalPush',
  }, {
    id: '0-1-0',
    name: '引导下载层',
    auth: 15,
    path: 'download',
  }, {
    id: '0-2',
    name: 'Where to Go City',
    auth: 15,
    path: 'wheretoGoCity',
  },
  {
    id: '0-3',
    name: '文章管理',
    auth: 15,
    path: 'article',
  }, {
    id: '1-0-0',
    auth: 15,
    name: 'Coupon',
    path: 'coupon',
  },
  {
    id: '1-0-1',
    auth: 15,
    name: 'Coupon Crossoer',
    path: 'coupon-cross',
  },
  {
    id: '1-0-2',
    auth: 15,
    name: 'Lucky Draw',
    path: 'lucky-draw',
  },
  {
    id: '1-0-3',
    auth: 15,
    name: 'Mini',
    path: 'mini',
  }, {
    id: '1-1-0',
    auth: 15,
    name: 'Special Event',
    path: 'special-event',
  },
  {
    id: '1-1-1',
    auth: 15,
    name: 'Special Event2',
    path: 'special-event2',
  }, {
    id: '1-2-0',
    auth: 15,
    name: '商品墙组件',
    path: 'commodity-wall',
  }, {
    id: '2-0-0',
    auth: 15,
    name: 'Flight Section',
    path: 'flight-section',
  },
  {
    id: '2-0-1',
    auth: 15,
    name: 'Hotel Section',
    path: 'hotel-section',
  },
  {
    id: '2-0-2',
    auth: 15,
    name: 'Where to Go背景',
    path: 'background',
  },
  {
    id: '2-0-3',
    auth: 15,
    name: 'Find Flights背景',
    path: 'backgroundFlights',
  },
  {
    id: '2-0-4',
    auth: 15,
    name: 'When to Go背景',
    path: 'backgroundGo',
  },
  {
    id: '2-0-5',
    auth: 15,
    name: '维护公告',
    path: 'notice',
  }, {
    id: '2-1',
    name: 'News',
    path: 'news',
    auth: 15,
  }, {
    id: '2-2-0',
    auth: 15,
    name: 'About Us',
    path: 'about-us',
  },
  {
    id: '2-2-1',
    name: 'Faq',
    auth: 15,
    path: 'faq',
  },
  {
    id: '2-2-2',
    auth: 15,
    name: 'Join Us',
    path: 'join-us',
  },
  {
    id: '2-2-3',
    auth: 15,
    name: 'Our Team',
    path: 'our-team',
  }, {
    id: '3-0-0',
    auth: 15,
    name: 'OTA Logo',
    path: 'ota-logo',
  },
  {
    id: '3-0-1',
    auth: 15,
    name: 'Airline Logo',
    path: 'airline-logo',
  }, {
    id: '3-1-0',
    auth: 15,
    name: 'PC-Flights-Web',
    path: 'languageWeb',
  },
  {
    id: '3-1-1',
    auth: 15,
    name: 'PC-Hotel-Web',
    path: 'languageHotel',
  },
  {
    id: '3-1-2',
    auth: 15,
    name: 'Mobile-Flights-Web',
    path: 'languageMobile',
  },
  {
    id: '3-1-3',
    auth: 15,
    name: 'Member-Web',
    path: 'languageMember',
  },
  {
    id: '3-1-4',
    auth: 15,
    name: 'B2B',
    path: 'languageB2B',
  },
  {
    id: '3-1-5',
    auth: 15,
    name: 'H5-Web',
    path: 'languageH5',
  },
  {
    id: '3-1-6',
    auth: 15,
    name: 'Hybrid-Hotel-APP',
    path: 'languageHotelAPP',
  },
  {
    id: '3-1-7',
    auth: 15,
    name: 'Hybrid-Flights-APP',
    path: 'languageFlightsAPP',
  }, {
    id: '3-2-0',
    name: '角色',
    auth: 15,
    path: 'role',
  },
  {
    id: '3-2-1',
    name: '用户',
    auth: 15,
    path: 'user',
  }, {
    name: '菜单管理',
    auth: 15,
    path: 'menuManage',
    id: '3-3',
  },
];

module.exports = modules;
